version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
  
  fastapi-app:
    build: .
    container_name: fastapi-container
    environment:
      host: "postgres"
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del contenedor al 3000 local
    volumes:
      - .:/app  # Monta todo el directorio actual en /app dentro del contenedor
    working_dir: /app  # Define el directorio de trabajo en el contenedor
    command: uvicorn main:app --host 0.0.0.0 --port 3000 --reload
volumes:
  postgres_data:

